### ISSUE TITLE
C工程的预测结果与matlab版本不同

### ISSUE THREAD

**Issue by Adarine99** [Jade999/face_antispoofing#9]
你好，
       我用matlab训练了自己的模型并且转成了dat,在matlab中预测结果还不错，但是相同的模型在C版本中预测一直为fake,请问你有没有遇到过这种问题，是加载模型或者提取特征过程有问题？还是其他的原因呢？
谢谢啦，祝好

**Comment by Jade999** [comment]
Matlab转c有很多要注意的地方，你可以阶段性对比中间的计算结果，查找可能有问题的地方，尤其注意matlab的数据存储方式
发自我的 iPhone

**Comment by Adarine99** [comment]
> 数据存储方式

好的，正在比对两种的方法的计算结果。非常感谢

**Comment by Adarine99** [comment]
> Matlab转c有很多要注意的地方，你可以阶段性对比中间的计算结果，查找可能有问题的地方，尤其注意matlab的数据存储方式 发自我的 iPhone
> […](#)
> 在 2018年12月14日，09:42，MTCNN ***@***.***> 写道： 你好， 我用matlab训练了自己的模型并且转成了dat,在matlab中预测结果还不错，但是相同的模型在C版本中预测一直为fake,请问你有没有遇到过这种问题，是加载模型或者提取特征过程有问题？还是其他的原因呢？ 谢谢啦，祝好 ― You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
你好，
       找到原因了，因为MATLAB's rgb2hsv() 和 OpenCV's cvtColor()的输出结果不同，造成提取特征的差异。超开心，谢谢～

**Comment by Adarine99** [comment]
> Matlab转c有很多要注意的地方，你可以阶段性对比中间的计算结果，查找可能有问题的地方，尤其注意matlab的数据存储方式 发自我的 iPhone
> […](#)
> 在 2018年12月14日，09:42，MTCNN ***@***.***> 写道： 你好， 我用matlab训练了自己的模型并且转成了dat,在matlab中预测结果还不错，但是相同的模型在C版本中预测一直为fake,请问你有没有遇到过这种问题，是加载模型或者提取特征过程有问题？还是其他的原因呢？ 谢谢啦，祝好 ― You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

你好，
       找到原因了，因为MATLAB's rgb2hsv() 和 OpenCV's cvtColor() 函数转换图像颜色空间时输出不同，提取特征存在差异，所以结果有问题。超开心，谢谢谢谢～
